services:
  - type: web
    name: digichamp-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
